apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  destination:
    namespace: firstapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev
    repoURL: https://github.com/Nandeesha23/argocd-demo.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: firstapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
