apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nandeesha23/argocd-demo.git
    targetRevision: HEAD
    path: argocd-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: firstapp
  syncPolicy:
    synchOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
